@startuml

[*] --> MENU
MENU : 1. PENJUMLAHAN
MENU : 2. PENGURANGAN
MENU : 3. PERKALIAN
MENU : 4. PEMBAGIAN
MENU --> PILIHAN
PILIHAN : Masukkan Pilihan Anda
PILIHAN --> PENJUMLAHAN: +
PILIHAN --> PENGURANGAN: -
PILIHAN --> PERKALIAN: *
PILIHAN --> PEMBAGIAN: :
@enduml